### ISSUE TITLE
Connection resets

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/diego-ssh#24]
Hi,

when using `cf ssh` we regularly see connection resets by the AWS ELB.

```
{"timestamp":"1475767567.461401463","source":"ssh-proxy","message":"ssh-proxy.cf-authenticate.exchange-access-code-for-token.request-failed","log_level":2,"data":{"error":"Post https://uaa.DOMAIN/oauth/token: read tcp ACCESS_IP:53202-\u003eELB_IP:443: read: connection reset by peer","session":"2661.1"}}
```

We are using CF v241 and diego v0.1483.0. But this errors occurs independently of the version.
Our ELB is configured with an Idle Connection Timeout of 400s (instead of the default, which is 60s).

When the timeout is reached, the ELB resets the connection...

```
09:16:34.072830 IP (tos 0x0, ttl 64, id 34451, offset 0, flags [DF], proto TCP (6), length 40)
     HOST.compute.amazonaws.com.https > access-z2-0.node.dc1.cf.internal.56320: Flags [R], cksum 0x58a1 (correct), seq 2596626333, win 346, length 0
```

... and ssh-proxy returns an error on the CLI

```
FAILED
Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

Currently no keepalive is used in the ssh-proxy [#353](https://github.com/cloudfoundry/diego-ssh/blob/ea7a826bf3647fab5b71206c00a2d671de452704/cmd/ssh-proxy/main.go#L353).

The golang [DefaultTransport/DefaultClient](https://golang.org/pkg/net/http/) is using a `KeepAlive` of 30s. We modified the ssh-proxy to use the same KeepAlive setting. This solved our problem.

Is there a specific reason not having a KeepAlive setting?

**Comment by achawki** [comment]
After some investigation we found out that the connection resets do not come from the elb. According to the [AWS documentation](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html#nat-gateway-troubleshooting-timeout) the NAT gateway has also a timeout of 5 minutes (in our test we experienced that it is slightly above 5 minutes).

When reducing the elb connection timeout to less than 5 min, we see that the ssh-proxy receives a FIN packet after a 5 minute idle connection, which we didn't receive before. Therefore the ssh-proxy opens a new TCP connection and we do not see the error described above anymore. 

A KeepAlive would enable a larger elb connection timeout.

**Comment by ematpl** [comment]
Thanks for the detailed investigation, @achawki. That change sounds reasonable, and I think it explains some flakiness we've seen with the `cf ssh` functionality in our build pipelines. I'll prioritize this issue for the Diego team to fix.

Best,
Eric, CF Runtime Diego PM

**Comment by ematpl** [comment]
Closing as accepted.
