### ISSUE TITLE
ssh-proxy logs don't contain the full command history

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/diego-ssh#34]
We are required by regulations to record and store every command run on our servers.

Currently ssh-proxy records the commands if you run them as follows:

```
cf ssh APP -c "<command>"
```

but if you open a shell session with `cf ssh` and then run `<command>` in it the logs won't contain which `<command>` was run.

Every command given, regardless if via `-c` or by opening a shell session, should be recorded in the logs.

**Comment by emalm** [comment]
Hi, @CAFxX,

Thanks for making us aware of this regulatory requirement, and my apologies for the delayed response. If you currently satisfy this requirement with other provisioning systems that allow SSH access to your servers (say, BOSH SSH, or direct SSH access to servers managed by other systems), how do you do so? What information about the commands the client passes to the shell do you capture in logs, and where are those logs generated and stored?

Thanks,
Eric, CF Diego PM

**Comment by CAFxX** [comment]
@emalm thanks for the reply, I'll get back to you with the details ASAP

**Comment by CAFxX** [comment]
@enalm our system security team currently records the following, on the jumpboxes for each command executed:
- user
- start date/time and duration of the command
- *command executed*
- *return code and full input and output of the command*

I'm trying to get permission to share more details - as you can imagine they are reluctant to discuss this openly.

**Comment by CAFxX** [comment]
@emalm gentle ping

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, and given current priorities and resource availability we're not going to be in a position to work on this so I'm going to go ahead and close it.
