### ISSUE TITLE
ssh-proxy better to have idle timeout for incoming connections

### ISSUE THREAD

**Issue by sunshineperi** [cloudfoundry/diego-ssh#36]
In our environment, a SLB is performing healthchecks by creating a tcp connection to ssh-proxy port 2222 and closing it with RST , but sometimes packet is lost due to bug of SLB or network problem, and in this case, the connection will always remain there as “ESTABLISHED”, which will finally make the connections being exhausted and users cannot ssh due to “too many open files”.  
It would be better to have this idle timeout provided and configurable within ssh-proxy.

Ps: asked in slack room but got no reply.  so submitted here and looking forward to any response.

**Comment by giner** [comment]
Ideally there should be 2 timeouts:
- connection timeout (when TCP connection is established and SSH session is not)
- session timeout (SSH session is established but there is no any activity)

The first timeout could be 5 seconds
The second one should be configurable with reasonable default, e.g. 5 minutes

**Comment by CAFxX** [comment]
@emalm just to summarize, the problem is that if a client opens a TCP connection and then sends no data at all the connection will never timeout (i.e. it's a very easy DoS vector).

In our case we noticed this because sometimes the RST packet from our SLB gets lost, and this basically will keep that TCP connection (and the goroutine) open forever.

**Comment by emalm** [comment]
Thanks for raising this issue, @sunshineperi, and for the additional context, @giner and @CAFxX. Agreed about the potential DoS vector, although from the initial description it sounds like the more immediate issue is that leaked client connections should eventually be closed so your load balancer doesn't exhaust the ssh-proxy's file descriptors. Prioritizing this for the Diego team to address: at first glance, I expect setting a moderate idle timeout would be effective, and we could also potentially increase the file descriptor limit that the ssh-proxy job sets to something large like 100,000, as we have already done with other services in diego-release.

Best,
Eric
