### ISSUE TITLE
Identify the diego-ssh server via ServerVersion

### ISSUE THREAD

**Issue by johnsonj** [cloudfoundry/diego-ssh#37]
# Background
diego-ssh/cmd/sshd identifies itself as `SSH-2.0-Go` which is the default value from the standard library. This prevents security scanning tools from properly identifying diego-ssh. 

This is important because the server identifies itself as accepting password authentication even though it's really a special OAuth flow which raises red flags for scanning tools. 

# How to verify
`$ ssh <diego-ssh> -vvv`

Look for:
```
debug1: Remote protocol version 2.0, remote software version Go
```

# Potential fix
Here's a patch I started but I'm having trouble getting everything to build. If you have a contributor guide I can take a crack at it or if you want to pick up this work that's great too.

```diff
diff --git a/cmd/sshd/main.go b/cmd/sshd/main.go
index 81286d0..ccd521c 100644
--- a/cmd/sshd/main.go
+++ b/cmd/sshd/main.go
@@ -182,7 +182,7 @@ func getDaemonEnvironment() map[string]string {
 
 func configure(logger lager.Logger) (*ssh.ServerConfig, error) {
 	errorStrings := []string{}
-	sshConfig := &ssh.ServerConfig{}
+	sshConfig := &ssh.ServerConfig{ServerVersion: "SSH-2.0-diego-ssh"}
 
 	key, err := acquireHostKey(logger)
 	if err != nil {
diff --git a/cmd/sshd/main_test.go b/cmd/sshd/main_test.go
index c823112..cbe7744 100644
--- a/cmd/sshd/main_test.go
+++ b/cmd/sshd/main_test.go
@@ -489,6 +489,12 @@ var _ = Describe("SSH daemon", func() {
 			client.Close()
 		})
 
+		Context("when a client connects", func() {
+			It("identifies itself as a diego-ssh server", func() {
+				Expect(client.Conn.ServerVersion()).To(Equal("SSH-2.0-diego-ssh"))
+			})
+		})
+
 		Context("when a client requests the execution of a command", func() {
 			It("runs the command", func() {
 				session, err := client.NewSession()
```

**Comment by emalm** [comment]
Thanks, @johnsonj! That server version change sounds reasonable, and we'd certainly accept the contribution if you're so inclined. We have contributing documents in diego-release at https://github.com/cloudfoundry/diego-release/blob/develop/CONTRIBUTING.md, if you want to take a shot at following them to make this change. We'd certainly appreciate feedback about them, too.

Best,
Eric, CF Diego PM
