### ISSUE TITLE
Allow Auditors to SSH into Diego cells with read only access

### ISSUE THREAD

**Issue by smoser-ibm** [cloudfoundry/diego-ssh#39]
Hello Diego Team, 

we have a customer request to allow auditors to SSH into Diego cells with read only access. The request basically says: with the implementation of Diego we should be able to SSH as auditors with read only access instead of having developer access and SSHing with root. Have you ever heard a similar request on your end and what is your take on it ? 

Alternatively, they would be also OK for them if CF provided a restore of the "files" functionality as it used to be in DEAs - i.e. to see the content of a container in read-only mode, e.g. for display in a UI. As yo know, this has been replaced with SSH which gives root permissions and there is not an option for read only. The initial Diego design notes said something like " this functionality might be restored a future point in time". Is this sentence still valid or what is your take on that ?

**Comment by emalm** [comment]
Hi, @smoser-ibm,

Thanks for asking about this: it's not something we have planned for the immediate future, but we have seen occasional requests for similar functionality.

Before we prioritize development of read-only modes for container access (whether that be closer to a `cf files` replacement or to a restricted SSH session), I'd like to know more about what activities this feature would support. Do you know what information an auditor would be interested in obtaining from the app instance filesystem and why, and at which point in its lifecycle (for example, starting, running, or recently crashed)? Would they require the ability to list directory contents, or only individual files? Are there other features of the previous `cf files` API they would expect to use, and if so, why? Also, by auditor, do you mean a "space auditor" in the sense of the roles that Cloud Controller provides, or something different?

Thanks,
Eric

**Comment by smoser-ibm** [comment]
Hey @emalm 

so we talked with them on the requirement again, and they require the ability to list directory contents, individual files and deployment logs. The intent is to be able to review deployments that happened but not being able to modify the contents. And they confirmed that they are talking about the space auditor role that should be able to do that.

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, and given current priorities and resource availability we're not going to be in a position to work on this so I'm going to go ahead and close it.
